title: "Alexssandro Santos — Data Engineering"
description: "Data Science and Data Engineering assets and projects"
baseurl: ""
url: ""
markdown: kramdown
theme: null
plugins: []
defaults:
  - scope: { path: "" }
    values:
      layout: default
author: "Alexssandro Santos"
github_username: "alexssandroos"
youtube_channel: "alexssandroos"
medium_username: "alexssandroos"
exclude:
  - "README.md"
